### ISSUE TITLE
IPv6 snapshot link returns 500 HTTP status code

### ISSUE THREAD

**Issue by vikulin** [yacy/yacy_search_server#225]
Stesps to reproduce:
1. Create a snapshot for IPv6 web site
2. Search such site and click on Snapshot link

Result:
HTTP ERROR 500
Problem accessing /root/yacy/DATA/HTCACHE/snapshots/inventory/[fc8b:5ec7:5c03:4eef:a666:fd71:2f35:55f6].80/01/cK/cK_zX7TJ5qXc.201809081225.xml. Reason:

    Illegal character in path at index 66: file:/root/yacy/htroot/root/yacy/DATA/HTCACHE/snapshots/inventory/[fc8b:5ec7:5c03:4eef:a666:fd71:2f35:55f6].80/01/cK/cK_zX7TJ5qXc.201809081225.class: /root/yacy/DATA/HTCACHE/snapshots/inventory/[fc8b:5ec7:5c03:4eef:a666:fd71:2f35:55f6].80/01/cK/cK_zX7TJ5qXc.201809081225.class

**Comment by luccioman** [comment]
@vikulin it looks like the issue only occurs when the DATA folder is on a file system that does not support the ':' character such as FAT32 or NTFS.

A fix is now available on latest sources, so if you can have a check your feedback will be welcome.

**Comment by vikulin** [comment]
No, it's Linux ext4 FS type

ср, 12 сент. 2018 г. в 18:39, luccioman <notifications@github.com>:

**Comment by luccioman** [comment]
Sorry @vikulin , you are right, I fixed a related but indeed different issue occurring at snapshot creation.

Is there also something traced in the logs?

Do you encounter the issue with other snapshots, especially with publicly available URLs so one can reproduce the issue?

**Comment by vikulin** [comment]
You can reproduce the issue by yourself opening following URL:
http://www.hyperborian.org/root/yacy/DATA/HTCACHE/snapshots/inventory/[fc79:1890:d724:d094:9665:cb32:cf34:255f].443/01/c5/c59atsy592M8.201809081225.xml

The log from yacy:
W 2018/09/13 10:48:42 ConcurrentLog java.nio.file.InvalidPathException:
Illegal character in path at index 66:
file:/root/yacy/htroot/root/yacy/DATA/HTCACHE/snapshots/inventory/[fc79:1890:d724:d094:9665:cb32:cf34:255f].443/01/c5/c59atsy592M8.201809081225.class:
/root/yacy/DATA/HTCACHE/snapshots/inventory/[fc79:1890:d724:d094:9665:cb32:cf34:255f].443/01/c5/c59atsy592M8.201809081225.class
java.nio.file.InvalidPathException: Illegal character in path at index 66:
file:/root/yacy/htroot/root/yacy/DATA/HTCACHE/snapshots/inventory/[fc79:1890:d724:d094:9665:cb32:cf34:255f].443/01/c5/c59atsy592M8.201809081225.class:
/root/yacy/DATA/HTCACHE/snapshots/inventory/[fc79:1890:d724:d094:9665:cb32:cf34:255f].443/01/c5/c59atsy592M8.201809081225.class
at
org.eclipse.jetty.util.resource.FileResource.addPath(FileResource.java:213)
at
net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:276)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
at
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
at
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at
net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33)
at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
at
org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)


чт, 13 сент. 2018 г. в 13:35, luccioman <notifications@github.com>:

**Comment by luccioman** [comment]
Ok, indeed it is not related to IPV6 : in the YaCy version you run the Snapshots links in the results are broken. But I also pushed a fix for that some time ago (see commit 4da15db9983f53be542147345c4ae355e8692656).
So you should upgrade your YaCy node to a more recent version to benefit from the fix.

**Comment by vikulin** [comment]
I can't upgrade since the official site <https://yacy.net/en/index.html> is
still showing an old release from 2016:
https://yacy.net/release/yacy_v1.92_20161226_9000.tar.gz

чт, 13 сент. 2018 г. в 16:03, luccioman <notifications@github.com>:

**Comment by luccioman** [comment]
Yes the main stable release is quite dated, but binaries are available for upgrade, depending on your setup. Notably :
- using your peer /ConfigUpdate_p.html admin page
- tar.gz archives for download at http://kaskelix.de/update/ or https://github.com/luccioman/yacy_search_server/releases (these repositories are used by the ConfigUpdate_p.html page)
- Debian repository at http://debian.yacy.net/ (but with a deprecated signing key size) or https://bintray.com/luccioman/yacy_search_server/yacy
- on Docker Hub at https://hub.docker.com/r/luccioman/yacy/ (daily built from latest sources)
- on Snapcraft store at https://snapcraft.io/yacy-search (still experimental, on the Edge channel only)

I hope this can help.

**Comment by vikulin** [comment]
Verified in dev version 1.921/9598

чт, 13 сент. 2018 г. в 19:31, luccioman <notifications@github.com>:
